version: "3.7"

services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: balinux/php
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - balinux-network

  # Nginx service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8085:80"
      - "7443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - balinux-network

  # MySQL service
  db:
    image: mariadb:10.4.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: ptsl
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - balinux-network

# Docker networks
networks:
  balinux-network:
    driver: bridge

# Docker volumes
volumes:
  dbdata:
    driver: local
